[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.format]
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
exclude = [".ruff_cache", "ui_.*\\.py$"]
fixable = ["ALL"]
ignore = []
select = ["F", "B", "I", "E", "W", "ANN", "TC"]

[tool.mypy]
mypy_path = python
exclude = [
  "ui_.*\\.py$",
]
explicit_package_bases = true
ignore_missing_imports = true
python_version = "3.11"
strict = true

[mypy-PySide6.*]
ignore_missing_imports = false
